/*
 *
 * Home constants
 *
 */

export const QUERY_PUBLIC_CLASSROOMS = 'app/Home/QUERY_PUBLIC_CLASSROOMS';
export const QUERY_PUBLIC_CLASSROOMS_SUCCESS = 'app/Home/QUERY_PUBLIC_CLASSROOMS_SUCCESS';
export const QUERY_PUBLIC_CLASSROOMS_ERROR = 'app/Home/QUERY_PUBLIC_CLASSROOMS_ERROR';

export const GENERATE_CLASSROOM = 'app/Home/GENERATE_CLASSROOM';
export const GENERATE_CLASSROOM_SUCCESS = 'app/Home/GENERATE_CLASSROOM_SUCCESS';
export const GENERATE_CLASSROOM_ERROR = 'app/Home/GENERATE_CLASSROOM_ERROR';

export const SEARCH_CLASSROOM = 'app/Home/SEARCH_CLASSROOM';
export const SEARCH_CLASSROOM_SUCCESS = 'app/Home/SEARCH_CLASSROOM_SUCCESS';
export const SEARCH_CLASSROOM_ERROR = 'app/Home/SEARCH_CLASSROOM_ERROR';
