/*
 *
 * Home constants
 *
 */

export const GENERATE_CLASSROOM = 'app/Home/GENERATE_CLASSROOM';
export const GENERATE_CLASSROOM_SUCCESS = 'app/Home/GENERATE_CLASSROOM_SUCCESS';
export const GENERATE_CLASSROOM_ERROR = 'app/Home/GENERATE_CLASSROOM_ERROR';

export const SEARCH_CLASSROOM = 'app/Home/SEARCH_CLASSROOM';
export const SEARCH_CLASSROOM_SUCCESS = 'app/Home/SEARCH_CLASSROOM_SUCCESS';
export const SEARCH_CLASSROOM_ERROR = 'app/Home/SEARCH_CLASSROOM_ERROR';
